// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjqs_D9E-xU9Nir6ML5q8Krp7TwDBg1-k',
    appId: '1:605306315512:web:a6733a8159dc61a128910d',
    messagingSenderId: '605306315512',
    projectId: 'morfhi-app',
    authDomain: 'morfhi-app.firebaseapp.com',
    storageBucket: 'morfhi-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHgfdCmzPQxVGuwCXvi8Ljtvh0Pg_amhQ',
    appId: '1:605306315512:android:558577a74c4ec64b28910d',
    messagingSenderId: '605306315512',
    projectId: 'morfhi-app',
    storageBucket: 'morfhi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHj4RwM4EkdRG9ULuW5ytzHgWapIOA6c',
    appId: '1:605306315512:ios:cf67ffc5487768c628910d',
    messagingSenderId: '605306315512',
    projectId: 'morfhi-app',
    storageBucket: 'morfhi-app.appspot.com',
    androidClientId: '605306315512-m9jg6ibsic1c3r59feiqee4q91gnl41a.apps.googleusercontent.com',
    iosClientId: '605306315512-tbg2lqvivbbhm2p22j4o5kgbl1k2ncv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.morfhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHj4RwM4EkdRG9ULuW5ytzHgWapIOA6c',
    appId: '1:605306315512:ios:cf67ffc5487768c628910d',
    messagingSenderId: '605306315512',
    projectId: 'morfhi-app',
    storageBucket: 'morfhi-app.appspot.com',
    androidClientId: '605306315512-m9jg6ibsic1c3r59feiqee4q91gnl41a.apps.googleusercontent.com',
    iosClientId: '605306315512-tbg2lqvivbbhm2p22j4o5kgbl1k2ncv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.morfhi',
  );
}
